fw.weapons.createGun("AK-47", {
	WorldModel = "models/weapons/w_rif_ak47.mdl",
	ViewModel = "models/weapons/v_rif_ak47.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_AK47.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Primary = {
		Ammo = "AR2",
		ClipSize = 30,
		DefaultClip = 60,
		Automatic = true,
		Damage = 27,
		RPM = 600,
		Sound = Sound("Weapon_AK47.Single"),
		BaseSpread = 0.02,
		BaseRecoil = 0.0075,
		MaxRecoil = 0.15,
	},
}, "fw_gun_ak47")

fw.weapons.createGun("AWP", {
	WorldModel = "models/weapons/w_snip_awp.mdl",
	ViewModel = "models/weapons/v_snip_awp.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	Slot = fw.weapons.SLOT_RIFLE,
	Scoped = true,
	ReloadSound = Sound("Weapon_AWP.Reload"),
	Primary = {
		Ammo = "AR2",
		ClipSize = 10,
		DefaultClip = 20,
		Automatic = false,
		Damage = 100,
		RPM = 41,
		Sound = Sound("Weapon_AWP.Single"),
		BaseSpread = 0,
		BaseRecoil = 0,
		MaxRecoil = 0,
	},
}, "fw_gun_awp")

fw.weapons.createGun("M3 Super 90", {
	WorldModel = "models/weapons/w_shot_m3super90.mdl",
	ViewModel = "models/weapons/v_shot_m3super90.mdl",
	ViewModelFlip = true,
	HoldType = "shotgun",
	Slot = fw.weapons.SLOT_SHOTGUN,
	ReloadSound = Sound("Weapon_M3.Reload"),
	Primary = {
		Ammo = "Buckshot",
		ClipSize = 8,
		DefaultClip = 16,
		Automatic = false,
		Damage = 14,
		RPM = 68,
		Sound = Sound("Weapon_M3.Single"),
		BaseSpread = 0.125,
		BaseRecoil = 0.05,
		MaxRecoil = 0.05,
		Bullets = 9,
		Shotgun = true,
	},
}, "fw_gun_m3")

fw.weapons.createGun("P90", {
	WorldModel = "models/weapons/w_smg_p90.mdl",
	ViewModel = "models/weapons/v_smg_p90.mdl",
	ViewModelFlip = true,
	HoldType = "smg",
	Slot = fw.weapons.SLOT_SMG,
	ReloadSound = Sound("Weapon_P90.Reload"),
	Primary = {
		Ammo = "SMG1",
		ClipSize = 50,
		DefaultClip = 100,
		Automatic = true,
		Damage = 14,
		RPM = 857,
		Sound = Sound("Weapon_P90.Single"),
		BaseSpread = 0.0175,
		BaseRecoil = 0.01,
		MaxRecoil = 0.25,
	},
}, "fw_gun_p90")

fw.weapons.createGun("Five-Seven", {
	WorldModel = "models/weapons/w_pist_fiveseven.mdl",
	ViewModel = "models/weapons/v_pist_fiveseven.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	Slot = fw.weapons.SLOT_PISTOL,
	ReloadSound = Sound("Weapon_Fiveseven.Reload"),
	Primary = {
		Ammo = "pistol",
		ClipSize = 20,
		DefaultClip = 40,
		Automatic = false,
		Damage = 30,
		RPM = 400,
		Sound = Sound("Weapon_Fiveseven.Single"),
		BaseSpread = 0.02,
		BaseRecoil = 0.005,
		MaxRecoil = 0.1,
	},
}, "fw_gun_fiveseven")