fw.weapons.createGun("AK-47", {
	WorldModel = "models/weapons/w_rif_ak47.mdl",
	ViewModel = "models/weapons/v_rif_ak47.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_AK47.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Primary = {
		Ammo = "AR2",
		ClipSize = 30,
		Automatic = true,
		Damage = 27,
		RPM = 600,
		Sound = Sound("Weapon_AK47.Single"),
		BaseSpread = 0.02,
		BaseRecoil = 0.0075,
		MaxRecoil = 0.15,
	},
}, "fw_gun_ak47")

fw.weapons.createGun("AWP", {
	WorldModel = "models/weapons/w_snip_awp.mdl",
	ViewModel = "models/weapons/v_snip_awp.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	Slot = fw.weapons.SLOT_RIFLE,
	Scoped = true,
	ReloadSound = Sound("Weapon_AWP.Reload"),
	Primary = {
		Ammo = "AR2",
		ClipSize = 10,
		Automatic = false,
		Damage = 100,
		RPM = 41,
		Sound = Sound("Weapon_AWP.Single"),
		BaseSpread = 0,
		BaseRecoil = 0,
		MaxRecoil = 0,
	},
}, "fw_gun_awp")

fw.weapons.createGun("M3 Super 90", {
	WorldModel = "models/weapons/w_shot_m3super90.mdl",
	ViewModel = "models/weapons/v_shot_m3super90.mdl",
	ViewModelFlip = true,
	HoldType = "shotgun",
	Slot = fw.weapons.SLOT_SHOTGUN,
	ReloadSound = Sound("Weapon_M3.Reload"),
	Primary = {
		Ammo = "Buckshot",
		ClipSize = 8,
		Automatic = false,
		Damage = 14,
		RPM = 68,
		Sound = Sound("Weapon_M3.Single"),
		BaseSpread = 0.125,
		BaseRecoil = 1,
		MaxRecoil = 0.2,
		Bullets = 9,
		Shotgun = true,
	},
}, "fw_gun_m3")

fw.weapons.createGun("P90", {
	WorldModel = "models/weapons/w_smg_p90.mdl",
	ViewModel = "models/weapons/v_smg_p90.mdl",
	ViewModelFlip = true,
	HoldType = "smg",
	Slot = fw.weapons.SLOT_SMG,
	ReloadSound = Sound("Weapon_P90.Reload"),
	Primary = {
		Ammo = "SMG1",
		ClipSize = 50,
		Automatic = true,
		Damage = 14,
		RPM = 857,
		Sound = Sound("Weapon_P90.Single"),
		BaseSpread = 0.05,
		BaseRecoil = 0.005,
		MaxRecoil = 0.05,
	},
}, "fw_gun_p90")

fw.weapons.createGun("Five-Seven", {
	WorldModel = "models/weapons/w_pist_fiveseven.mdl",
	ViewModel = "models/weapons/v_pist_fiveseven.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	Slot = fw.weapons.SLOT_PISTOL,
	ReloadSound = Sound("Weapon_Fiveseven.Reload"),
	Primary = {
		Ammo = "pistol",
		ClipSize = 20,
		Automatic = false,
		Damage = 24,
		RPM = 400,
		Sound = Sound("Weapon_Fiveseven.Single"),
		BaseSpread = 0.02,
		BaseRecoil = 0.005,
		MaxRecoil = 0.1,
	},
}, "fw_gun_fiveseven")

fw.weapons.createGun("Desert Eagle", {
	WorldModel = "models/weapons/w_pist_deagle.mdl",
	ViewModel = "models/weapons/v_pist_deagle.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	ReloadSound = Sound("Weapon_Deagle.Reload"),
	Slot = fw.weapons.SLOT_PISTOL,
	Primary = {
		Ammo = "pistol",
		ClipSize = 7,
		Automatic = false,
		Damage = 41,
		RPM = 100,
		Sound = Sound("Weapon_Deagle.Single"),
		BaseSpread = 0.04,
		BaseRecoil = 0.0175,
		MaxRecoil = 0.2,
	},
}, "fw_gun_deagle")

fw.weapons.createGun("Dualies", {
	WorldModel = "models/weapons/w_pist_elite.mdl",
	ViewModel = "models/weapons/v_pist_elite.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	ReloadSound = Sound("Weapon_Elite.Reload"),
	Slot = fw.weapons.SLOT_PISTOL,
	Primary = {
		Ammo = "pistol",
		ClipSize = 20,
		Automatic = false,
		Damage = 15,
		RPM = 510,
		Sound = Sound("Weapon_Elite.Single"),
		BaseSpread = 0.05,
		BaseRecoil = 0.0075,
		MaxRecoil = 0.12,
	},
}, "fw_gun_dualies")

fw.weapons.createGun("Glock", {
	WorldModel = "models/weapons/w_pist_glock18.mdl",
	ViewModel = "models/weapons/v_pist_glock18.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	ReloadSound = Sound("Weapon_Glock.Reload"),
	Slot = fw.weapons.SLOT_PISTOL,
	Primary = {
		Ammo = "pistol",
		ClipSize = 18,
		Automatic = false,
		Damage = 16,
		RPM = 400,
		Sound = Sound("Weapon_Glock.Single"),
		BaseSpread = 0.021,
		BaseRecoil = 0.0075,
		MaxRecoil = 0.08,
		BurstFire = true,
		BurstAmount = 3,
	},
}, "fw_gun_glock")

fw.weapons.createGun("P228", {
	WorldModel = "models/weapons/w_pist_p228.mdl",
	ViewModel = "models/weapons/v_pist_p228.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	ReloadSound = Sound("Weapon_P228.Reload"),
	Slot = fw.weapons.SLOT_PISTOL,
	Primary = {
		Ammo = "pistol",
		ClipSize = 12,
		Automatic = false,
		Damage = 24,
		RPM = 425,
		Sound = Sound("Weapon_P228.Single"),
		BaseSpread = 0.03,
		BaseRecoil = 0.0055,
		MaxRecoil = 0.1,
	},
}, "fw_gun_p228")

fw.weapons.createGun("USP", {
	WorldModel = "models/weapons/w_pist_usp.mdl",
	ViewModel = "models/weapons/v_pist_usp.mdl",
	ViewModelFlip = true,
	HoldType = "pistol",
	ReloadSound = Sound("Weapon_USP.Reload"),
	Slot = fw.weapons.SLOT_PISTOL,
	Primary = {
		Ammo = "pistol",
		ClipSize = 12,
		Automatic = false,
		Damage = 18,
		RPM = 400,
		Sound = Sound("Weapon_USP.Single"),
		BaseSpread = 0.015,
		BaseRecoil = 0.0035,
		MaxRecoil = 0.04,
	},
}, "fw_gun_usp")

fw.weapons.createGun("AUG", {
	WorldModel = "models/weapons/w_rif_aug.mdl",
	ViewModel = "models/weapons/v_rif_aug.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_AUG.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Scoped = true,
	Primary = {
		Ammo = "AR2",
		ClipSize = 30,
		Automatic = true,
		Damage = 25,
		RPM = 575,
		Sound = Sound("Weapon_AUG.Single"),
		BaseSpread = 0.02,
		BaseRecoil = 0.0045,
		MaxRecoil = 0.1,
	},
}, "fw_gun_aug")

fw.weapons.createGun("Famas", {
	WorldModel = "models/weapons/w_rif_famas.mdl",
	ViewModel = "models/weapons/v_rif_famas.mdl",
	ViewModelFlip = false,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_FAMAS.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Primary = {
		Ammo = "AR2",
		ClipSize = 25,
		Automatic = true,
		Damage = 20,
		RPM = 725,
		Sound = Sound("Weapon_FAMAS.Single"),
		BaseSpread = 0.023,
		BaseRecoil = 0.0045,
		MaxRecoil = 0.1,
		BurstFire = true,
		BurstAmount = 3,
	},
}, "fw_gun_famas")

fw.weapons.createGun("Galil", {
	WorldModel = "models/weapons/w_rif_galil.mdl",
	ViewModel = "models/weapons/v_rif_galil.mdl",
	ViewModelFlip = false,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_Galil.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Primary = {
		Ammo = "AR2",
		ClipSize = 35,
		Automatic = true,
		Damage = 20,
		RPM = 650,
		Sound = Sound("Weapon_Galil.Single"),
		BaseSpread = 0.02,
		BaseRecoil = 0.065,
		MaxRecoil = 0.13,
	},
}, "fw_gun_galil")

fw.weapons.createGun("M4A1", {
	WorldModel = "models/weapons/w_rif_m4a1.mdl",
	ViewModel = "models/weapons/v_rif_m4a1.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_M4A1.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Primary = {
		Ammo = "AR2",
		ClipSize = 20,
		Automatic = true,
		Damage = 26,
		RPM = 625,
		Sound = Sound("Weapon_M4A1.Single"),
		BaseSpread = 0.013,
		BaseRecoil = 0.006,
		MaxRecoil = 0.1,
	},
}, "fw_gun_m4a1")

fw.weapons.createGun("SG552", {
	WorldModel = "models/weapons/w_rif_sg552.mdl",
	ViewModel = "models/weapons/v_rif_sg552.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	ReloadSound = Sound("Weapon_SG552.Reload"),
	Slot = fw.weapons.SLOT_RIFLE,
	Scoped = true,
	Primary = {
		Ammo = "AR2",
		ClipSize = 25,
		Automatic = true,
		Damage = 22,
		RPM = 600,
		Sound = Sound("Weapon_SG552.Single"),
		BaseSpread = 0.015,
		BaseRecoil = 0.01,
		MaxRecoil = 0.1,
	},
}, "fw_gun_sg552")

fw.weapons.createGun("XM-1014", {
	WorldModel = "models/weapons/w_shot_xm1014.mdl",
	ViewModel = "models/weapons/v_shot_xm1014.mdl",
	ViewModelFlip = true,
	HoldType = "shotgun",
	Slot = fw.weapons.SLOT_SHOTGUN,
	ReloadSound = Sound("Weapon_XM1014.Reload"),
	Primary = {
		Ammo = "Buckshot",
		ClipSize = 8,
		Automatic = true,
		Damage = 13,
		RPM = 108,
		Sound = Sound("Weapon_XM1014.Single"),
		BaseSpread = 0.15,
		BaseRecoil = 0.3,
		MaxRecoil = 0.2,
		Bullets = 11,
		Shotgun = true,
	},
}, "fw_gun_xm1014")

fw.weapons.createGun("Mac 10", {
	WorldModel = "models/weapons/w_smg_mac10.mdl",
	ViewModel = "models/weapons/v_smg_mac10.mdl",
	ViewModelFlip = true,
	HoldType = "smg",
	Slot = fw.weapons.SLOT_SMG,
	ReloadSound = Sound("Weapon_Mac10.Reload"),
	Primary = {
		Ammo = "SMG1",
		ClipSize = 30,
		Automatic = true,
		Damage = 12,
		RPM = 1250,
		Sound = Sound("Weapon_Mac10.Single"),
		BaseSpread = 0.052,
		BaseRecoil = 0.01,
		MaxRecoil = 0.35,
	},
}, "fw_gun_mac10")

fw.weapons.createGun("MP5", {
	WorldModel = "models/weapons/w_smg_mp5.mdl",
	ViewModel = "models/weapons/v_smg_mp5.mdl",
	ViewModelFlip = true,
	HoldType = "smg",
	Slot = fw.weapons.SLOT_SMG,
	ReloadSound = Sound("Weapon_MP5Navy.Reload"),
	Primary = {
		Ammo = "SMG1",
		ClipSize = 30,
		Automatic = true,
		Damage = 19,
		RPM = 800,
		Sound = Sound("Weapon_MP5Navy.Single"),
		BaseSpread = 0.015,
		BaseRecoil = 0.0075,
		MaxRecoil = 0.2,
	},
}, "fw_gun_mp5")

fw.weapons.createGun("TMP", {
	WorldModel = "models/weapons/w_smg_tmp.mdl",
	ViewModel = "models/weapons/v_smg_tmp.mdl",
	ViewModelFlip = true,
	HoldType = "smg",
	Slot = fw.weapons.SLOT_SMG,
	ReloadSound = Sound("Weapon_TMP.Reload"),
	Primary = {
		Ammo = "SMG1",
		ClipSize = 30,
		Automatic = true,
		Damage = 14,
		RPM = 1000,
		Sound = Sound("Weapon_TMP.Single"),
		BaseSpread = 0.05,
		BaseRecoil = 0.002,
		MaxRecoil = 0.3,
	},
}, "fw_gun_tmp")

fw.weapons.createGun("UMP", {
	WorldModel = "models/weapons/w_smg_ump45.mdl",
	ViewModel = "models/weapons/v_smg_ump45.mdl",
	ViewModelFlip = true,
	HoldType = "smg",
	Slot = fw.weapons.SLOT_SMG,
	ReloadSound = Sound("Weapon_ump45.Reload"),
	Primary = {
		Ammo = "SMG1",
		ClipSize = 30,
		Automatic = true,
		Damage = 17,
		RPM = 720,
		Sound = Sound("Weapon_ump45.Single"),
		BaseSpread = 0.015,
		BaseRecoil = 0.003,
		MaxRecoil = 0.25,
	},
}, "fw_gun_ump")

fw.weapons.createGun("Scout", {
	WorldModel = "models/weapons/w_snip_scout.mdl",
	ViewModel = "models/weapons/v_snip_scout.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	Slot = fw.weapons.SLOT_RIFLE,
	Scoped = true,
	ReloadSound = Sound("Weapon_Scout.Reload"),
	Primary = {
		Ammo = "AR2",
		ClipSize = 10,
		Automatic = false,
		Damage = 80,
		RPM = 67,
		Sound = Sound("Weapon_Scout.Single"),
		BaseSpread = 0,
		BaseRecoil = 0,
		MaxRecoil = 0,
	},
}, "fw_gun_scout")

fw.weapons.createGun("G3SG1", {
	WorldModel = "models/weapons/w_snip_g3sg1.mdl",
	ViewModel = "models/weapons/v_snip_g3sg1.mdl",
	ViewModelFlip = true,
	HoldType = "AR2",
	Slot = fw.weapons.SLOT_RIFLE,
	Scoped = true,
	ReloadSound = Sound("Weapon_G3SG1.Reload"),
	Primary = {
		Ammo = "AR2",
		ClipSize = 10,
		Automatic = true,
		Damage = 65,
		RPM = 170,
		Sound = Sound("Weapon_G3SG1.Single"),
		BaseSpread = 0.015,
		BaseRecoil = 0,
		MaxRecoil = 0,
	},
}, "fw_gun_g3sg1")